function classify_stop()

% List of training images
train_pics = { ...
                'donotenter1.jpg'; ...
                'donotenter2.jpg'; ...
                'speed1.jpg'; ...
                'speed2.jpg'; ...
                'speed3.jpg'; ...
                'speed4.jpg'; ...
                'wrongway1.jpg'; ...
                'wrongway2.jpg'; ...
                'wrongway3.jpg'; ...
                'wrongway4.jpg'; ...
                'wrongway5.jpg'; ...
                'yield1.jpg'; ...
                'yield2.jpg'; ...
                'yield3.jpg'; ...
                'yield4.jpg'; ...
                'stop1.jpg'; ...
                'stop2.jpg'; ...
                'stop3.jpg'; ...
                'stop4.jpg'; ...
                'stop5.jpg'; ...
                'stop6.jpg'; ...
                'stop7.jpg'; ...
                'stop8.jpg'; ...
                'stop9.jpg'; ...
                'stop10.jpg'; ...
                'stop11.jpg'; ...
                'stop12.jpg'; ...
                'stop13.jpg'; ...
                'stop14.jpg'; ...
                'stop15.jpg';
            };
        
% List of testing images
test_pics = { ...
                'donotenter3.jpg'; ...
                'speed5.jpg'; ...
                'speed6.jpg'; ...
                'speed7.jpg'; ...
                'speed8.jpg'; ...
                'speed9.jpg'; ...
                'speed10.jpg'; ...
                'speed11.jpg'; ...
                'speed12.jpg'; ...
                'speed13.jpg'; ...
                'speed14.jpg'; ...
                'speed15.jpg'; ...
                'speed16.jpg'; ...
                'speed17.jpg'; ...
                'stop16.jpg'; ...
                'stop17.jpg'; ...
                'stop18.jpg'; ...
                'stop19.jpg'; ...
                'stop20.jpg'; ...
                'stop21.jpg'; ...
                'stop22.jpg'; ...
                'stop23.jpg'; ...
                'stop24.jpg'; ...
                'stop25.jpg'; ...
                'stop26.jpg'; ...
                'wrongway6.jpg'; ...
                'wrongway7.jpg'; ...
                'wrongway8.jpg'; ...
                'wrongway9.jpg'; ...
                'wrongway10.jpg'; ...
                'wrongway11.jpg'; ...
                'wrongway12.jpg'; ...
                'yield5.jpg'; ...
                'yield6.jpg'; ...
                'yield7.jpg'; ...
                'yield8.jpg'; ...
                'yield9.jpg'; ...
                'yield10.jpg'; ...
                'yield11.jpg'; ...
                'yield12.jpg'; ...
                'yield13.jpg'; ...
                'yield14.jpg';
            };

% Create labels
train_labels = [zeros(15,1); ones(15,1)];
test_labels = [zeros(14,1); ones(11,1); zeros(17,1)];
        
% Load images
n_train_pics = size(train_pics, 1);
n_test_pics = size(test_pics, 1);
train_data = zeros(n_train_pics, 1151880);
test_data = train_data;
for i = 1:n_train_pics
    impath = ['..\ref\' train_pics{i,1}];
    im = imread(impath);
    imsize = prod(size(im));
    train_data(i,(1:imsize)) = reshape(im, [1 imsize]);
end

for i = 1:n_test_pics
    impath = ['..\ref\' test_pics{i,1}];
    im = imread(impath);
    imsize = prod(size(im));
    test_data(i,(1:imsize)) = reshape(im, [1 imsize]);
end

model = lintrain(train_labels, sparse(train_data), '-s 6 -c 1e6  -p 0.1');

[labels, acc, prob] = linpredict(test_labels, sparse(test_data), model);

disp('end')

end
